<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Submit' => 'Submit',
    'Your account has been successfully saved' => 'Your account has been successfully saved',
    'About' => 'About',
    'Account' => 'Account',
    'Articles' => 'Articles',
    'Attachments' => 'Attachments',
    'Backend' => 'Backend',
    'Body' => 'Body',
    'Check your email for further instructions.' => 'Check your email for further instructions.',
    'Confirm Password' => 'Confirm Password',
    'Contact' => 'Contact',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Error while oauth process.',
    'Female' => 'Female',
    'Home' => 'Home',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'If you forgot your password you can reset it <a href="{link}">here</a>',
    'Incorrect username or password.' => 'Incorrect username or password.',
    'Language' => 'Language',
    'Log in with' => 'Log in with',
    'Login' => 'Login',
    'Logout' => 'Logout',
    'Male' => 'Male',
    'Name' => 'Name',
    'Need an account? Sign up.' => 'Need an account? Sign up.',
    'New password was saved.' => 'New password was saved.',
    'Page not found' => 'Page not found',
    'Password' => 'Password',
    'Password reset for {name}' => 'Password reset for {name}',
    'Profile' => 'Profile',
    'Remember Me' => 'Remember Me',
    'Request password reset' => 'Request password reset',
    'Reset password' => 'Reset password',
    'Sign up with' => 'Sign up with',
    'Signup' => 'Signup',
    'Sorry, we are unable to reset password for email provided.' => 'Sorry, we are unable to reset password for email provided.',
    'Subject' => 'Subject',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Thank you for contacting us. We will respond to you as soon as possible.',
    'There was an error sending email.' => 'There was an error sending email.',
    'This email address has already been taken.' => 'This email address has already been taken.',
    'This username has already been taken.' => 'This username has already been taken.',
    'Update' => 'Update',
    'Username' => 'Username',
    'Username or email' => 'Username or email',
    'Verification Code' => 'Verification Code',
    'We already have a user with email {email}' => 'We already have a user with email {email}',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Welcome to {app-name}. Email with your login information was sent to your email.',
    'Your profile has been successfully saved' => 'Your profile has been successfully saved',
    '{app-name} | Your login information' => '{app-name} | Your login information',
];
