<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Last login' => 'Đăng nhập lần cuối',
    'Updated at' => 'Chỉnh sửa lúc',
    '"{attribute}" must be a valid JSON' => '"{attribute}" phải là một JSON',
    'Active' => 'Active',
    'Administrator' => 'Administrator',
    'Article ID' => 'Article ID',
    'Author' => 'Tác giả',
    'Base Url' => 'Base Url',
    'Body' => 'Body',
    'Caption' => 'Caption',
    'Carousel ID' => 'Carousel ID',
    'Category' => 'Category ',
    'Comment' => 'Comment',
    'Component' => 'Component',
    'Config' => 'Config',
    'Created At' => 'Thêm lúc',
    'Created at' => 'Thêm lúc',
    'Deleted' => 'Đã xóa',
    'Down to maintenance.' => 'Down to maintenance',
    'E-mail' => 'E-mail',
    'Firstname' => 'Tên',
    'Gender' => 'Giới tính',
    'ID' => 'ID',
    'Key' => 'Key',
    'Lastname' => 'Họ',
    'Locale' => 'Locale',
    'Manager' => 'Manager',
    'Middlename' => 'Middlename',
    'Name' => 'Name',
    'Order' => 'Order',
    'Parent Category' => 'Danh mục cha',
    'Path' => 'Path',
    'Picture' => 'Picture',
    'Published' => 'Published',
    'Published At' => 'Published At',
    'Role' => 'Role',
    'Size' => 'Size',
    'Slug' => 'Slug',
    'Status' => 'Status',
    'Title' => 'Tiêu đề',
    'Type' => 'Loại',
    'Updated At' => 'Cập nhật lúc',
    'Updater' => 'Người cập nhật',
    'Upload Ip' => 'Upload Ip',
    'Url' => 'Url',
    'User' => 'User',
    'User ID' => 'User ID',
    'Username' => 'Username',
    'Value' => 'Value',
	'Not Deleted' => 'Not Deleted',
	'Approved' => 'Approved',
	'Not Approved' => 'Not Approved',
	'City' => 'City',
	'District' => 'District',
	'Ward' => 'Ward',
	'Street' => 'Street',
	'Address' => 'Address',
	'Phone' => 'Phone',
	'Website' => 'Website',
	'Email' => 'Email',
	'Lng' => 'Lng',
	'Lat' => 'Lat'
];
