<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Submit' => 'Đăng',
    'Your account has been successfully saved' => 'Tài khoản của bạn đã được lưu',
    'About' => 'About',
    'Account' => 'Tài khoản',
    'Articles' => 'Bài viết',
    'Attachments' => 'Đính kèm',
    'Backend' => 'Backend',
    'Body' => 'Body',
    'Check your email for further instructions.' => 'Check your email for further instructions.',
    'Confirm Password' => 'Xác nhận mật khẩu',
    'Contact' => 'Liên hệ',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Error while oauth process.',
    'Female' => 'Nữ',
    'Home' => 'Trang chủ',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Nếu bạn đã quên mật khẩu bạn có thể reset mật khẩu bằng link <a href="{link}">này</a>',
    'Incorrect username or password.' => 'Sai tên người dùng hoặc mật khẩu.',
    'Language' => 'Ngôn ngữ',
    'Log in with' => 'Đăng nhập với',
    'Login' => 'Đăng nhập',
    'Logout' => 'Đăng xuất',
    'Male' => 'Nam',
    'Name' => 'Name',
    'Need an account? Sign up.' => 'Chưa có tài khoản? Đăng ký',
    'New password was saved.' => 'Mật khẩu mới đã được lưu',
    'Page not found' => 'Không tìm thấy trang',
    'Password' => 'Mật khẩu',
    'Password reset for {name}' => 'Reset mật khẩu cho {name}',
    'Profile' => 'Thông tin cá nhân',
    'Remember Me' => 'Ghi nhớ',
    'Request password reset' => 'Yêu cầu reset mật khẩu',
    'Reset password' => 'Reset mật khẩu',
    'Sign up with' => 'Đăng ký với',
    'Signup' => 'Đăng ký',
    'Sorry, we are unable to reset password for email provided.' => 'Xin lỗi, chúng tôi không thể reset mật khẩu cho email đã cung cấp.',
    'Subject' => 'Tiêu đề',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Cảm ơn bạn đã liên hệ chúng tôi. Chúng tôi sẽ phản hồi ngay khi có thể',
    'There was an error sending email.' => 'Đã xảy ra lỗi trong quá trình gửi mail.',
    'This email address has already been taken.' => 'Địa chỉ email này đã được sử dụng',
    'This username has already been taken.' => 'Tên người dùng đã được sử dụng',
    'Update' => 'Cập nhật',
    'Username' => 'Tên người dùng',
    'Username or email' => 'Tên người dùng hoặc e-mail',
    'Verification Code' => 'Mã xác nhận',
    'We already have a user with email {email}' => 'Địa chỉ email({email}) này đã được sử dụng.',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Chào mừng bạn đến với {app-name}. E-mail chứa thông tin đăng nhập đã được gửi.',
    'Your profile has been successfully saved' => 'Thông tin cá nhân của bạn đã được lưu',
    '{app-name} | Your login information' => '{app-name} | THông tin đăng nhập',
];
